"""initial migration

Revision ID: 8a44361f9ac4
Revises: None
Create Date: 2016-07-01 09:28:47.442544

"""

# revision identifiers, used by Alembic.
revision = '8a44361f9ac4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'date_created')
    ### end Alembic commands ###
